INSERT INTO USERS (ID, USERNAME, EMAIL, PASSWORD, ROLE) VALUES (0, 'admin', 'admin@gmail.com', 'admin', 'ADMIN');
INSERT INTO USERS (ID, USERNAME, EMAIL, PASSWORD, ROLE) VALUES (1, 'da', 'dasauto@gmail.com', 'da', 'USER');


INSERT INTO STORAGE (ID, COLOR, NAME, SIZE, PRICE) VALUES (0, 'blue', 'flask', '1L', 5400);

INSERT INTO DEPOSITORY (ID, ADDRESS) VALUES (0,'Kalvin_ter_2');
--INSERT INTO DEPOSITORY (ID, ADDRESS) VALUES (1,'Fovam_ter_4');

INSERT INTO QUANTITY (ID,COMMENT, QUANTITY, DEPOSITORY_ID, PRODUCT_ID) VALUES (0, 'kek', 6, 0, 0);

--INSERT INTO ISSUES(ID,VERSION,DESCRIPTION,LOCATION,STATUS, TIMESTAMP) VALUES (0,0,'projektor elromlott','123','ADDED',CURRENT_TIMESTAMP())