INSERT INTO USERS (ID, USERNAME, EMAIL, PASSWORD, ROLE) VALUES (0, 'admin', 'admin@gmail.com', 'admin', 'ADMIN');

INSERT INTO STORAGE (ID, COLOR, NAME, SIZE, PRICE) VALUES (0, 'blue', 'flask', '1L', 5400);

--INSERT INTO ISSUES(ID,VERSION,DESCRIPTION,LOCATION,STATUS, TIMESTAMP) VALUES (0,0,'projektor elromlott','123','ADDED',CURRENT_TIMESTAMP())